title: "Matteo Durando's Portfolio"
description: "A showcase of my projects, skills, and interests."
theme: jekyll-theme-cayman
url: "https://matteod00.github.io"
baseurl: ""
locale: "en"
name: "Matteo Durando"
repository: "MatteoD00/matteod00.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

github:
  username: MatteoD00
