title: "Matteo Durando's Portfolio"
description: "A showcase of my projects, skills, and interests."
remote_theme: pages-themes/slate@v0.2.0
# theme: minima
url: "https://matteod00.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-fontawesome
  - jekyll-remote-theme
  - jekyll-feed

github:
  username: MatteoD00
#  token: ${{ secrets.GITHUB_TOKEN }}