title: "Matteo Durando's Portfolio"
description: "A showcase of my projects, skills, and interests."
theme: minima # You can replace this with any Jekyll theme
url: "https://matteod00.github.io"
baseurl: ""

navigation:
  - name: "Home"
    link: "/home/"
  - name: "About"
    link: "/about/"
  - name: "Contacts"
    link: "/contacts/"
