title: "Matteo Durando's Portfolio"
description: "A showcase of my projects, skills, and interests."
theme: minima # You can replace this with any Jekyll theme
url: "https://matteod00.github.io"
baseurl: ""

plugins:
  - jekyll-github-metadata
  - jemoji

github:
  username: MatteoD00
#  token: ${{ secrets.GITHUB_TOKEN }}  # This will pull the token securely from GitHub Secrets
