title: "Matteo Durando's Portfolio"
description: "A showcase of my projects, skills, and interests."
#remote_theme: pages-themes/primer@v0.6.0
theme: jekyll-theme-primer
url: "https://matteod00.github.io"
baseurl: ""
locale: "en"
name: "Matteo Durando"
repository: "MatteoD00/matteod00.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-github-metadata
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-fontawesome
  - jekyll-remote-theme
  - jekyll-feed

github:
  username: MatteoD00
#  token: ${{ secrets.GITHUB_TOKEN }}